Repository meilisearch/mini-dashboard, pull requests merged in 2021-07, with the labels that each got.

#89 Remove Storybook from dependabot
  .github/dependabot.yml
Labels: skip-changelog

#83 Add Cypress
  .eslintrc.json
  .github/workflows/tests.yml
  .gitignore
  bors.toml
  cypress.json
  cypress/integration/test-api-key.js
  cypress/integration/test-no-meilisearch.js
  package.json
  yarn.lock
Labels: skip-changelog

#94 Fix highlight inside links
  src/components/Results/Hit.js
Labels: bug

#98 Update Select component
  src/components/Select.js
Labels: skip-changelog

#101 Add MeiliSearch version
  src/App.js
  src/components/Header/index.js
Labels: enhancement

#106 Update version to 0.1.4
  package.json
Labels: skip-changelog

#107 Update publish build workflow
  .github/workflows/publish-build.yml
Labels: skip-changelog

#108 Update node version in publish build
  .github/workflows/publish-build.yml
Labels: skip-changelog

#109 Update build path
  .github/workflows/publish-build.yml
Labels: skip-changelog

#110 Use upload-release-action v2
  .github/workflows/publish-build.yml
Labels: skip-changelog

#111 Update contributing with release process
  CONTRIBUTING.md
Labels: skip-changelog
