Repository meilisearch/mini-dashboard, pull requests merged in 2023-07, with the labels that each got.

#442 Add a call to action banner for the cloud
  .eslintrc.json
  src/App.js
  src/components/CloudBanner.js
  src/components/Link.js
  src/components/Typography.js
Labels: enhancement

#453 Added api-key warning banner
  src/App.js
  src/components/ApiKeyAwarenessBanner.js
  src/components/Header/index.js
  src/components/Typography.js
  src/components/icons/AlertCircle.js
  src/components/icons/index.js
  src/components/icons/svg/alert-circle.svg
Labels: enhancement

#456 Fix bug where interface crashes if hit has no field
  src/components/Results/Hit.js
  src/components/Results/index.js
Labels: bug

#460 Disable eslint error on a console warning
  src/components/Results/Hit.js
Labels: skip-changelog

#461 Update link to the cloud page
  src/components/CloudBanner.js
Labels: skip-changelog

#464 Revert changes introducing a better way to render large index lists
  cypress/e2e/test-interface.cy.js
  cypress/e2e/test-select-indexes.cy.js
  package.json
  src/components/Results/InfiniteHits.js
  src/components/Select.js
  yarn.lock
Labels: bug
